import type { Metadata } from 'next';
import React from 'react';
import { Inter } from 'next/font/google';

import '@/style/index.css';

import ConvexClerkProvider from '@/app/ConvexClerkProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Podcast',
    description: 'Generated by create next app',
    icons: {
        icon: '/icons/logo.svg',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ConvexClerkProvider>{children}</ConvexClerkProvider>
            </body>
        </html>
    );
}
